[package]
name = "bobobot"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenvy = "0.15.7"
poise = "0.6.1"
rand = "0.8.5"
serenity = "0.12.2"
tokio = { version = "1.40.0", features = ["full"] }
